apiVersion: v1
kind: ReplicationController
metadata:
  namespace: librum-ci
  labels:
    name: librum-ci-master
  name: librum-ci-master-controller
spec:
  replicas: 1
  selector:
    name: librum-ci-master
  template:
    metadata:
      labels:
        name: librum-ci-master
    spec:
      containers:
      - image: toeknee/librum-ci-master:0.01
        imagePullPolicy: Always
        name: librum-ci-master
        ports:
        - containerPort: 8080
          name: http-server
        env:
        - name: NODE_ENV
          value: production
        - name: DOCKER_HUB_USER
          valueFrom:
            secretKeyRef:
              name: docker-hub-creds
              key: docker-hub-user
