apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-controller
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    name: redis
    mode: standalone
  template:
    metadata:
      labels:
        name: redis
        mode: standalone
    spec:
      containers:
      - name: redis
        image: redis:3.0.7
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data/db
      volumes:
        - name: redis-persistent-storage
          gcePersistentDisk:
            pdName: redis-disk
            fsType: ext4
