apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: librum-ci
  name: nfs-pv-provisioning
  labels:
    name: nfs-pv-provisioning
  annotations:
    volume.alpha.kubernetes.io/storage-class: any
spec:
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 200Gi
