apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: librum-ci
  name: nfs
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.3.240.178 # FIXME: use the right IP
    path: "/exports"
