apiVersion: v1
kind: Service
metadata:
  namespace: librum-ci
  labels:
    name: mongo
    visualize: 'true'
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
