FROM toeknee/librum-ci-xenial-node:0.01

##### Docker
ENV DEBIAN_FRONTEND noninteractive
RUN set -ex \
  && apt-get install -y --force-yes apt-transport-https ca-certificates \
  && apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \
  && echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list \
  && apt-get update \
  && apt-get install -y --force-yes docker-engine
